### ISSUE TITLE
Redux does not clear data when log out

### ISSUE THREAD

**Issue by Tommy2212** [Tommy2212/hansae-dashboard#1]
Redux does not clear data when log out. Please try to figure out the issue and fix it.

**Comment by doantrung1997** [comment]
<h2>Description:</h2>

Because `apolloClient`  from **apollo-client.ts** in `src\@core\apollo-client\apollo-client.ts` path that still hold cached value.

<h2>Solution</h2>

- create new function is `clearApolloClient()` that will reset cache `apolloClient?.cache.reset()`, and set `apolloClient = undefined`
![image](https://github.com/Tommy2212/hansae-dashboard/assets/30361153/ba48b943-8734-47ea-a6d3-fe54542cc552)

- In function **handleLogout()** in **UserDropdown.tsx** in path: **`src\@core\layouts\components\shared-components\UserDropdown.tsx** will call clearApolloClient()
![image](https://github.com/Tommy2212/hansae-dashboard/assets/30361153/8cabf54b-ba9b-4ceb-9738-06dce4c6758d)

**Comment by Tommy2212** [comment]
Will handleLogout() be called in UserDropdown.tsx  or AuthContext.tsx ?

**Comment by doantrung1997** [comment]
Yes, it should be called in AuthContext.tsx, I edited the previous comment
